module.exports = {
  authors: [
    {
      author_name: "Scott Adams",
      university: "Harvard University",
      date_of_birth: "1952-07-10",
      h_index: 40,
      gender: "m",
      mentor: 3,
    },
    {
      author_name: "Michael Abrash",
      university: "University of Oxford",
      date_of_birth: "1957-11-12",
      h_index: 60,
      gender: "m",
      mentor: 4,
    },
    {
      author_name: "Tarn Adams",
      university: "University of Washington",
      date_of_birth: "1978-04-17",
      h_index: 100,
      gender: "m",
      mentor: 2,
    },
    {
      author_name: "Leonard Adleman",
      university: "University of California",
      date_of_birth: "1945-12-31",
      h_index: 130,
      gender: "m",
      mentor: 3,
    },
    {
      author_name: "Alfred Aho",
      university: "University of Toronto",
      date_of_birth: "1941-08-09",
      h_index: 90,
      gender: "m",
      mentor: 4,
    },
    {
      author_name: "Andrei Alexandrescu",
      university: "Politehnica University of Bucharest",
      date_of_birth: "1969-01-01",
      h_index: 50,
      gender: "m",
      mentor: 5,
    },
    {
      author_name: "Paul Allen",
      university: "Washington State University",
      date_of_birth: "1953-01-21",
      h_index: 200,
      gender: "m",
      mentor: 1,
    },
    {
      author_name: "Eric Paul Allman",
      university: "University of California",
      date_of_birth: "1955-09-02",
      h_index: 50,
      gender: "m",
      mentor: 5,
    },
    {
      author_name: "Marc Andreessen",
      university: "University of Illinois",
      date_of_birth: "1971-07-09",
      h_index: 90,
      gender: "m",
      mentor: 7,
    },
    {
      author_name: "Jeremy Ashkenas",
      university: "Harvard University",
      date_of_birth: "1976-10-10",
      h_index: 20,
      gender: "m",
      mentor: 13,
    },
    {
      author_name: "Bill Atkinson",
      university: "University of California",
      date_of_birth: "1951-03-17",
      h_index: 200,
      gender: "m",
      mentor: 6,
    },
    {
      author_name: "Adele Goldberg",
      university: "University of Michigan",
      date_of_birth: "1945-07-22",
      h_index: 60,
      gender: "f",
      mentor: 12,
    },
    {
      author_name: "Emily Short",
      university: "Harvard University",
      date_of_birth: "1970-03-11",
      h_index: 90,
      gender: "f",
      mentor: 14,
    },
    {
      author_name: "Sophie Wilson",
      university: "University of Cambridge",
      date_of_birth: "1957-04-10",
      h_index: 2,
      gender: "f",
      mentor: 11,
    },
    {
      author_name: "Jamie Zawinski",
      university: "Harvard University",
      date_of_birth: "1968-11-03",
      h_index: 20,
      gender: "m",
      mentor: 13,
    },
  ],

  researchPapers: [
    {
      paper_title: "GITLAB COMMIT VIRTUAL",
      conference: "DevOps",
      publish_date: "2021-08-04",
      author_no: 3,
    },
    {
      paper_title: "BLACK HAT USA",
      conference: "Security",
      publish_date: "2021-08-05",
      author_no: 5,
    },
    {
      paper_title: "ROADMAP TO BILLIONS",
      conference: "Tech leadership",
      publish_date: "2021-08-12",
      author_no: 7,
    },
    {
      paper_title: "AGILE LEAN",
      conference: "Agile",
      publish_date: "2020-01-30",
      author_no: 10,
    },
    {
      paper_title: "REFACTR.TECH",
      conference: "Full-stack",
      publish_date: "2019-04-22",
      author_no: 6,
    },
    {
      paper_title: "ROADMAP TO BILLIONS",
      conference: "Tech leadership",
      publish_date: "2021-08-12",
      author_no: 8,
    },
    {
      paper_title: "ZERONIGHTS",
      conference: "Security",
      publish_date: "2021-08-25",
      author_no: 10,
    },
    {
      paper_title: "PYCONLINE AU",
      conference: "Python",
      publish_date: "2020-10-30",
      author_no: 5,
    },
    {
      paper_title: "REACT DAY",
      conference: "Frontend",
      publish_date: "2020-10-20",
      author_no: 5,
    },
    {
      paper_title: "PYCONLINE AU",
      conference: "Python",
      publish_date: "2020-10-30",
      author_no: 12,
    },
    {
      paper_title: "ROADMAP TO BILLIONS",
      conference: "Tech leadership",
      publish_date: "2021-08-12",
      author_no: 13,
    },
    {
      paper_title: "QUBIT",
      conference: "Security",
      publish_date: "2020-10-12",
      author_no: 1,
    },
    {
      paper_title: "ACCENTO",
      conference: "Java",
      publish_date: "2020-10-12",
      author_no: 2,
    },
    {
      paper_title: "EUROSTAR",
      conference: "QA / Testing",
      publish_date: "2018-12-10",
      author_no: 4,
    },
    {
      paper_title: "STRANGE LOOP",
      conference: "Full-stack",
      publish_date: "2010-01-06",
      author_no: 3,
    },
    {
      paper_title: "CLOJUTRE",
      conference: "Functional programming",
      publish_date: "2020-09-25",
      author_no: 4,
    },
    {
      paper_title: "VUEJS GLOBAL",
      conference: "Frontend",
      publish_date: "2016-08-23",
      author_no: 9,
    },
    {
      paper_title: "ACCU AUTUMN",
      conference: "C/C++",
      publish_date: "2019-01-13",
      author_no: 11,
    },
    {
      paper_title: "HACKER HALTED",
      conference: "Security",
      publish_date: "2019-09-24",
      author_no: 15,
    },
    {
      paper_title: "API WORLD",
      conference: "Full-stack",
      publish_date: "2020-01-17",
      author_no: 12,
    },
    {
      paper_title: "BLOCKCHAIN LIFE",
      conference: "Blockchain",
      publish_date: "2020-08-30",
      author_no: 11,
    },
    {
      paper_title: "CODE.TALKS",
      conference: "Full-stack",
      publish_date: "2018-01-10",
      author_no: 7,
    },
    {
      paper_title: "IT NONSTOP",
      conference: "Data science / ML",
      publish_date: "2010-05-09",
      author_no: 3,
    },
    {
      paper_title: "PYCON APAC",
      conference: "Python",
      publish_date: "2017-03-03",
      author_no: 1,
    },
    {
      paper_title: "XTREME PYTHON",
      conference: "Python",
      publish_date: "2020-11-02",
      author_no: 13,
    },
    {
      paper_title: "EVOLUTIONARY DESIGN",
      conference: "Software architecture",
      publish_date: "2019-03-10",
      author_no: 7,
    },
    {
      paper_title: "XTREME JS",
      conference: "JavaScript",
      publish_date: "2020-10-04",
      author_no: 1,
    },
    {
      paper_title: "DEVNEXUS",
      conference: "JAVA",
      publish_date: "2021-07-19",
      author_no: 6,
    },
    {
      paper_title: "CPPNORTH",
      conference: "C/C++",
      publish_date: "2020-10-20",
      author_no: 5,
    },
    {
      paper_title: "NORDIC.JS",
      conference: "Javascript",
      publish_date: "2021-02-21",
      author_no: 9,
    },
  ],
};
